const styles = {
  '@global': {
    html: {
      scrollBehavior: 'smooth',
    },
    '@keyframes fadeInUp': {
      from: { opacity: 0, transform: 'translateY(20px)' },
      to: { opacity: 1, transform: 'translateY(0)' },
    },
    '& section': { animation: '$fadeInUp 0.8s ease-out' },
  },
  container: {
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: 'background.default',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    paddingTop: '80px',
  },
  hero: {
    position: 'relative',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    color: '#fff',
    padding: '0 24px',
    overflow: 'hidden',
    background: 'rgba(0,0,0,0.7)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundBlendMode: 'overlay',
  },
  avatar: {
    width: 140,
    height: 140,
    margin: '0 auto 24px',
    border: '6px solid #fff',
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'scale(1.08)',
      boxShadow: '0 0 24px rgba(255, 0, 127, 0.5)',
    },
  },
  heroTitle: {
    fontWeight: 800,
    lineHeight: 1.2,
    marginBottom: '16px',
    color: '#fff',
    textShadow: '0 2px 8px rgba(0,0,0,0.2)',
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.9)',
    marginBottom: '32px',
    fontWeight: 500,
    fontSize: '1.25rem',
    textShadow: '0 2px 8px rgba(0,0,0,0.2)',
    maxWidth: '800px',
    mx: 'auto',
  },
  downloadBtn: {
    mt: 5,
    px: 4,
    py: 1.5,
    borderRadius: '24px',
    fontWeight: 700,
    boxShadow: '0 4px 14px rgba(255, 64, 129, 0.3)',
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 8px 20px rgba(255, 64, 129, 0.4)',
    },
    background: 'linear-gradient(to right, #ff4081, #e91e63)',
    color: '#fff',
  },
  heroContent: {
    position: 'relative',
    zIndex: 2,
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '40px 24px 80px',
    borderRadius: '16px',
    backgroundColor: 'rgba(25,25,25,0.25)',
    backdropFilter: 'blur(6px)',
  },
    // --- NAVBAR ---
    navbar: {
  position: 'fixed',
  top: 0,
  left: 0,
  width: '100%',
  zIndex: 1200,
  display: 'flex',
  scrollMarginTop: '100px', 
  alignItems: 'center',
  justifyContent: 'space-between',
  flexWrap: 'wrap', // ✅ helps with mobile
  padding: '16px 32px',
  backgroundColor: 'rgba(255,255,255,0.15)',
  backdropFilter: 'blur(12px)',
  boxShadow: '0 2px 24px rgba(0,0,0,0.1)',
  borderBottom: '1px solid rgba(255,255,255,0.18)',
  '@media (max-width: 600px)': {
    flexDirection: 'column',
    gap: '10px',
    alignItems: 'center',
    padding: '12px 16px',
  },
},
        navTitle: {
  fontFamily: "'Poppins', sans-serif",
  fontSize: '1.5rem',
  scrollMarginTop: '100px',
  fontWeight: 700,
  color: '#000',
  textShadow: '0 2px 8px rgba(0,0,0,0.1)',
  marginRight: '20px',
  transition: 'all 0.3s ease',
  '&:hover': {
    color: '#ff4081',
    transform: 'scale(1.02)',
  },
  '@media (max-width: 600px)': {
    margin: '0 auto 6px',
    textAlign: 'center',
  },
},
    navLinks: {
  display: 'flex',
  marginRight:'50px',
  flexWrap: 'wrap',
  justifyContent: 'center', // ✅ full centering
  gap: '50px',
  overflowX: 'auto',
  scrollMarginTop: '100px', 
  whiteSpace: 'nowrap',
  padding: '8px 0',
  scrollbarWidth: 'none',
  msOverflowStyle: 'none',
  '&::-webkit-scrollbar': {
    display: 'none',
  },
  '@media (max-width: 600px)': {
    gap: '12px',
    justifyContent: 'center', // ✅ consistent
  },
},
    navLink: {
  color: '#333',
  textDecoration: 'none',
  fontWeight: 500,
  fontSize: '1.05rem',
  position: 'relative',
  scrollMarginTop: '100px', 
  paddingBottom: '2px',
  transition: 'all 0.3s ease',

  '&::after': {
    content: '""',
    position: 'absolute',
    bottom: '-4px',
    left: 0,
    width: '100%',
    height: '2px',
    scrollMarginTop: '100px', 
    backgroundColor: '#ff4081',
    transform: 'scaleX(0)',
    transformOrigin: 'left',
    transition: 'transform 0.3s ease',
  },

  '&:hover::after': {
    transform: 'scaleX(1)',
  },

  '&:hover': {
    color: '#ff4081', // ✅ more readable than white
  },

  '@media (max-width: 600px)': {
    fontSize: '0.95rem',
  },
},

    // --- CONTACT FORM ---
    contactFormCard: {
        padding: '40px',
        maxWidth: '600px',
        margin: '0 auto',
        background: 'linear-gradient(135deg, rgba(255,255,255,0.9) 0%, rgba(247,247,247,0.95) 100%)',
        borderRadius: '16px',
        boxShadow: '0 16px 32px rgba(0,0,0,0.1)',
        border: '1px solid rgba(255,255,255,0.3)',
        transition: 'all 0.3s ease',
        '&:hover': {
            boxShadow: '0 24px 48px rgba(0,0,0,0.15)',
            transform: 'translateY(-4px)',
        },
        '@media (max-width: 600px)': {
            padding: '32px 16px',
            maxWidth: '90%',
        },
    },
    contactFormField: {
        mb: 3,
        '& .MuiOutlinedInput-root': {
            borderRadius: '8px',
            backgroundColor: 'rgba(255,255,255,0.85)',
            '& fieldset': {
            borderColor: 'rgba(0,0,0,0.1)',
            },
            '&:hover fieldset': {
            borderColor: 'rgba(0,0,0,0.2)',
            },
            '&.Mui-focused fieldset': {
            borderColor: '#ff4081',
            borderWidth: '2px',
            },
        },
    '& .MuiInputLabel-root': {
            color: '#666',
            '&.Mui-focused': {
            color: '#ff4081',
            },
        },
    },
    contactFormButton: {
  mt: 3,
  px: 4,
  py: 1.5,
  borderRadius: '8px',
  fontWeight: 600,
  background: 'linear-gradient(to right, #ff4081, #e91e63)',
  color: '#fff',
  transition: 'all 0.3s ease',
  '&:hover': {
    background: 'linear-gradient(to right, #e91e63, #c2185b)',
    transform: 'translateY(-2px)',
  },
  alignSelf: 'center',
  width: 'fit-content',
},

    section: {
        padding: '64px 24px',
        textAlign: 'center',
        backgroundColor: '#f9f9f9',
    },
  sectionWithImage: {
  position: 'relative',
  py: 10,
  px: { xs: 2, sm: 3, md: 4 },
  color: '#fff',
  overflow: 'hidden',
  minHeight: '350px',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundSize: 'cover',
  backgroundPosition: 'center',
  backgroundRepeat: 'no-repeat',
  backgroundBlendMode: 'overlay',
},

    sectionContent: {
    position: 'relative',
    zIndex: 2,
    maxWidth: '1200px',
    width: '100%',
    margin: '0 auto',
    animation: '$fadeInUp 0.8s ease-out',
    backgroundColor: 'rgba(238, 238, 238, 0.95)',
    color: '#1e1e1e',
    scrollMarginTop: '100px',
    borderRadius: '16px',
    padding: '32px 24px',
    boxShadow: '0 16px 32px rgba(0,0,0,0.15)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    },
  sectionTitle: {
    fontWeight: 700,
    fontSize: 'clamp(1.75rem, 4vw, 2.5rem)',
    textAlign: 'center',
    mb: 4,
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: '-12px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '100px',
      height: '4px',
      background: 'linear-gradient(to right, #ff4081, #e91e63)',
      borderRadius: '2px',
    },
  },
  card: {
    p: 4,
    borderRadius: '16px',
    backgroundColor: '#fff',
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'translateY(-6px)',
      boxShadow: '0 12px 24px rgba(0,0,0,0.1)',
    },
    minHeight: '180px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  bigCard: {
    p: 3,
    borderRadius: '16px',
    backgroundColor: '#fff',
    boxShadow: '0 8px 16px rgba(0,0,0,0.1)',
    transition: 'all 0.3s ease',
    minHeight: '140px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 12px 24px rgba(0,0,0,0.15)',
    },
  },
  cardWithImage: {
    p: 3,
    borderRadius: '16px',
    backgroundColor: '#fff',
    boxShadow: '0 8px 16px rgba(0,0,0,0.1)',
    transition: 'all 0.3s ease',
    minHeight: '340px',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 12px 24px rgba(0,0,0,0.15)',
    },
  },
  cardWithIcon: {
    p: 4,
    borderRadius: '16px',
    backgroundColor: '#fff',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    minHeight: '240px',
    justifyContent: 'center',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 12px 24px rgba(0,0,0,0.1)',
    },
  },
  projectLinks: {
  display: 'flex',
  gap: '16px',
  mt: 2,
  justifyContent: 'center',
  flexWrap: 'wrap',
  '& a': {
    px: 2,
    py: 0.75,
    borderRadius: '20px',
    textDecoration: 'none',
    color: '#fff',
    fontWeight: 600,
    background: 'linear-gradient(to right, #ff4081, #e91e63)',
    transition: 'all 0.3s ease',
    '&:hover': {
      background: 'linear-gradient(to right, #e91e63, #c2185b)',
      transform: 'translateY(-2px)',
    },
  },
},

  footer: {
    textAlign: 'center',
    py: 6,
    mt: 8,
    backgroundColor: 'rgba(238, 238, 238, 0.95)',
    borderRadius: '16px 16px 0 0',
    boxShadow: '0 -8px 16px rgba(0,0,0,0.1)',
  },
  socialIcons: {
    display: 'flex',
    justifyContent: 'center',
    gap: 4,
    mb: 2,
    '& a': {
      transition: 'all 0.2s ease',
      color: '#666',
      '&:hover': { transform: 'scale(1.2)', color: '#e91e63' },
    },
  },
};

export default styles;
